apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshbg
spec:
  destination:
    namespace: freshbg
    server: https://kubernetes.default.svc
  project: default
  source:
    path: freshbg
    repoURL: GIT-REPO
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true